### ISSUE TITLE
Freezing Xcode7 UITests

### ISSUE THREAD

**Issue by zhigang1992** [applanga/sdk-ios#1]
First of all, awesome project. :+1: 

But seems like it's breaking Xcode7 UITests

I've a demo project prepared

https://github.com/zhigang1992/AppLangaUITestBug

<img width="1512" alt="screen shot 2015-10-29 at 8 39 12 pm" src="https://cloud.githubusercontent.com/assets/1057756/10818520/228d9e60-7e7d-11e5-926f-913e0ddfc33b.png">

It hangs on `wait for app to idle` and then failed with timeout.

Can you guys help me out on this?

btw, is there a plan for Open Source? 

:smile:

**Comment by steffen-roemer** [comment]
Hi Sorry for the late reply. The Issue was fixed quite a while ago but the Ticket got lost. There is a plan but not yet fully decided. 

best regards Steffen
