### ISSUE TITLE
String with arguments removing texts with "\n"

### ISSUE THREAD

**Issue by brunohenriquesk1** [applanga/sdk-ios#10]
If you have a String with `\n` on the dashboard for example "%{duration} \n per day" calling `Applanga.localizedString` will remove`\n`

Note: Your iOS documentation is outdated. `getString` is not available anymore.

**Comment by applanga-rich** [comment]
Hi, thanks for the report, i'm looking into it now

**Comment by applanga-rich** [comment]
I can confirm that this happens and we are working on how to address it.

In the mean time, here is a simple workaround:

Instead of using the \n symbol in the dash, you can actually hit the enter/return key while editing the text on the dashboard and that will create a new line that is recognised by the dashboard and the sdk.

**Comment by brunohenriquesk1** [comment]
@applanga-rich I tried adding only space as you suggested on the dashboard and the output is the same, it won't recognize the space when the string has named arguments.

**Comment by applanga-rich** [comment]
This issue is closed as it is not reproducible. Please contact support@applanga.com if you require further support

**Comment by Konstantin-GoStartups** [comment]
@applanga-rich Having the same issue here. Also with current version of iOS SDK when I add  "\n" in the localisable string it doesn't recognise it as a new line and shows it like that: "Something\n".

**Comment by applanga-rich** [comment]
hi @Konstantin-GoStartups Do you mean when you add \n in the string file in the Xcode project or when you add it in the Applanga dashboard?

**Comment by steffen-roemer** [comment]
This issue is closed as it is not reproducible. Please contact support@applanga.com if you require further support
