### ISSUE TITLE
iOS 15 upgrade losing data

### ISSUE THREAD

**Issue by RichP** [applanga/sdk-ios#12]
We are seeing an issue after upgrading from iOS 14 to iOS 15.  The user is presented with an Alert that says "Applanga Settings File missing or outdated!" and the app starts to show Applanga keys instead of translated text.   Force killing the app from the task switcher and relaunching makes everything work again.

These are not new builds but, existing production apps that were already working on the users device prior to upgrading to iOS 15.

**Comment by steffen-roemer** [comment]
with sdk version 2.0.150 this should hopefully be resolved
