### ISSUE TITLE
Cannot use enable_bitcode option because Applanga doesn't provide full bitcode.

### ISSUE THREAD

**Issue by EugeneEl** [applanga/sdk-ios#4]
Hi, when I'm trying to build app with Applanga I got the following output.
I'm using fastlane but seems issue is related to Applanga.

Environment:  
latest version of Applanga installed via Cocoapods - "Applanga (2.0.80)"
Xcode Version 8.3.3 (8E3004b)
CocoaPods - 1.0.1
   
Output:
ld: bitcode bundle could not be generated because
Pods/Applanga/Applanga.framework/Applanga' was built without full bitcode.

Currently I totally disabled bitcode in options but wonder is it possible to resolve this issue?
Thanks.

**Comment by steffen-roemer** [comment]
Hi Eugene,
thank you for the report its very strange in our tests its working fine with bitcode enabled could you maybe try a later cocoapods version or provide a sample app with the issue?
best regards,
Steffen

**Comment by steffen-roemer** [comment]
Hi @EugeneGoloboyar 
we've found and fixed the issue in version 2.0.81 thank you for the report!
cheers,
Steffen
