### ISSUE TITLE
Carthage --platform iOS results in error

### ISSUE THREAD

**Issue by ghost** [applanga/sdk-ios#5]
Using carthage we have plenty of dependencies that would require --platform iOS to not get bogged down by unnecessary platforms building.

An error is thrown when adding Applanga to the Cartfile

*** Skipped building sdk-ios due to the error:
Dependency "sdk-ios" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/applanga/sdk-ios/issues/new

Can Applanga add the platform iOS to the framework schemes

**Comment by steffen-roemer** [comment]
could you please post how you added applanga to your Cartfile?

**Comment by ghost** [comment]
@applanga-sroemer 

`github "applanga/sdk-ios" ~> 2.0`

then

` carthage update --platform iOS --no-use-binaries`

**Comment by ghost** [comment]
@applanga-sroemer  Hey any update?

**Comment by steffen-roemer** [comment]
Hi the problem originates from your usage of --no-use-binaries so if you remove that it should work fine. It seems to be a limitation/bug in current carthage versions whereas it can not recognize a binary only framework from github that has build with objective-c and tries to rebuild it.

**Comment by steffen-roemer** [comment]
Hi @lockett-rccl 
we've extendend our carthage deployment so if you change
`github "applanga/sdk-ios" ~> 2.0`
to
`binary "https://raw.githubusercontent.com/applanga/sdk-ios/master/Applanga.json" ~> 2.0`
in your Cartfile it should now work even with `--no-use-binaries`

**Comment by ghost** [comment]
@applanga-sroemer Okay, but when using --platform iOS the scheme does not build then the framework does not work.

**Comment by steffen-roemer** [comment]
I'm not sure if i understand your issue since it works fine on our tests.
`carthage update --platform iOS --no-use-binaries`
with
`binary "https://raw.githubusercontent.com/applanga/sdk-ios/master/Applanga.json" ~> 2.0`
works fine now right?
If not please provide me with the error message.

And if thats not the error please elaborate on that and provide a error message if possible.
