### ISSUE TITLE
Upload key without default value

### ISSUE THREAD

**Issue by davidblaesing** [applanga/sdk-ios#7]
Can you support uploading keys to applanga via debugattached when no defaultvalue is given?
For example:
```swift
// Should upload a key with empty translation.
Applanga.localizedString(forKey: "translationkey", withDefaultValue: nil)
// Currently nothing will uploaded
```

**Comment by applanga-rich** [comment]
This issue is closed due to inactivity. Please contact support@applanga.com if you require further support
