### ISSUE TITLE
The application is freezing and crashing in the initial setup

### ISSUE THREAD

**Issue by edgarivan89** [applanga/sdk-ios#8]
While running some test I noticed in the log that Applanga initial setup is taking more than 10 seconds so the OS is killing the app, only with bad network condition, if I run the same test without internet it's loading without issues so maybe you need to add a timeout 

Conditions
iOS : 12.4
iPhone: 6, 7
Very Bad Network simulated with Network Link Conditioner
![IMG_0004](https://user-images.githubusercontent.com/20785356/62678594-ec6c0c80-b97f-11e9-820d-1776b7dc9f86.jpg)

Log
`2019-08-08 01:39:08.397270-0400 App[1559:274500] I/Applanga﹕ Version: 2.0.126
2019-08-08 01:39:08.406583-0400 App[1559:274500] I/Applanga﹕ Strings will NOT be uploaded. Neither the debugger is connected nor the app is in draft mode!
2019-08-08 01:39:21.084101-0400 App[1559:274498] I/Applanga﹕ initialized!`

Crash report
`Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-create watchdog transgression: com.app.greatapp exhausted real (wall clock) time allowance of 7.55 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 56.660 (user 56.660, system 0.000), 94% CPU", | "Elapsed application CPU time (seconds): 1.329, 2% CPU" | )
Triggered by Thread:  0`

**Comment by applanga-rich** [comment]
This issue is closed due to inactivity. Please contact support@applanga.com if you require further support
